{{ if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}
  labels:
    app: {{ .Values.global.appName }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
    spec:
      containers:
        - name: {{ .Values.global.appName }}
          image: "{{ .Values.deployment.image.repository }}/{{ .Values.global.appName }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          envFrom:
            {{- toYaml .Values.deployment.envFrom | nindent 12 }}
          env:
              {{- toYaml .Values.deployment.env | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
{{ end }}