{{ if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}
  labels:
    app: {{ .Values.global.appName }}
    app.kubernetes.io/name: {{ .Values.global.appName }}
    app.kubernetes.io/instance: {{ .Values.global.appName }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  strategy:
    type: {{ .Values.deployment.strategy.type | default "RollingUpdate" }}
    {{ if eq .Values.deployment.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.deployment.strategy.maxSurge | default "25%" }}
      maxUnavailable: {{ .Values.deployment.strategy.maxUnavailable | default "25%" }}
    {{ end }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
    spec:
      {{ with .Values.deployment.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.deployment.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      {{ if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{ end }}
      containers:
        - name: {{ .Values.global.appName }}
          image: "{{ .Values.deployment.image.repository }}/{{ .Values.global.appName }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{ with .Values.deployment.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.deployment.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.deployment.env }}
          env:
              {{- toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.deployment.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{ end }}:
          {{ with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          {{ with .Values.deployment.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{ end }}
      restartPolicy: {{ .Values.deployment.restartPolicy | default "Always" }}
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds | default 30 }}
      dnsPolicy: {{ .Values.deployment.dnsPolicy | default "ClusterFirst" }}
      securityContext: {}
      schedulerName: {{ .Values.deployment.schedulerName | default "default-scheduler" }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit | default 5 }}
  progressDeadlineSeconds: {{ .Values.deployment.progressDeadlineSeconds | default 600 }}
{{ end }}